"""
Test script for PnL correlation-based diversity analysis

This script demonstrates how to calculate and visualize PnL diversity.
"""

import sys
from pathlib import Path

# Add project root to Python path
project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

import pandas as pd
from gp_quant.diversity import DiversityAnalyzer
from gp_quant.diversity.visualizer import DiversityVisualizer

# Configuration (relative to project root)
RECORDS_DIR = str(project_root / "experiments_results/ABX_TO/individual_records_long_run01")
TICKER = "ABX.TO"
DATA_FILE = str(project_root / f"TSE300_selected/{TICKER}.csv")

# Backtest period (should match the experiment configuration)
TRAIN_DATA_START = '1992-06-30'
TRAIN_BACKTEST_START = '1993-07-02'
TRAIN_BACKTEST_END = '1999-06-25'

# Sampling configuration (for performance)
SAMPLE_SIZE = 50  # Sample 50 individuals per generation instead of all 500

print("="*80)
print("🧪 Testing PnL Correlation-based Diversity Analysis")
print("="*80)
print()

# Step 1: Load market data
print("1. Loading market data...")
data = pd.read_csv(DATA_FILE, index_col=0, parse_dates=True)
print(f"   ✓ Loaded {len(data)} days of data for {TICKER}")
print(f"   Date range: {data.index[0].date()} to {data.index[-1].date()}")
print()

# Step 2: Initialize analyzer
print("2. Initializing diversity analyzer...")
analyzer = DiversityAnalyzer(RECORDS_DIR)
print(f"   ✓ Analyzer created for: {RECORDS_DIR}")
print()

# Step 3: Load populations
print("3. Loading populations...")
populations = analyzer.load_populations(verbose=True)
print(f"   ✓ Loaded {len(populations)} generations")
print()

# Step 4: Check if correlation matrices already exist
import os
correlation_summary_file = str(project_root / "correlation_matrices/correlation_summary.csv")

if os.path.exists(correlation_summary_file):
    print("4. Loading pre-calculated correlation data...")
    print(f"   Found: {correlation_summary_file}")
    print(f"   (This data was generated by export_correlation_matrices.py)")
    print()
    
    # Load the pre-calculated data
    correlation_data = pd.read_csv(correlation_summary_file)
    
    # Rename columns to match expected format
    pnl_diversity_data = correlation_data.rename(columns={
        'corr_mean': 'pnl_corr_mean',
        'corr_std': 'pnl_corr_std',
        'corr_min': 'pnl_corr_min',
        'corr_max': 'pnl_corr_max',
        'corr_median': 'pnl_corr_median',
        'n_valid_individuals': 'valid_individuals',
        'n_pairs': 'total_pairs'
    })
    
    print(f"   ✓ Loaded data for {len(pnl_diversity_data)} generations")
    print()
else:
    print("4. Calculating PnL correlation diversity...")
    print(f"   Using sample size: {SAMPLE_SIZE} individuals per generation")
    print(f"   This may take a few minutes...")
    print()
    print(f"   ⚠️  Recommendation: Run 'export_correlation_matrices.py' first")
    print(f"      for more reliable results with larger sample size.")
    print()

    pnl_diversity_data = analyzer.calculate_pnl_diversity_trends(
        data=data,
        backtest_start=TRAIN_BACKTEST_START,
        backtest_end=TRAIN_BACKTEST_END,
        sample_size=SAMPLE_SIZE,
        verbose=True
    )

    print()
    print(f"   ✓ Calculated PnL diversity for {len(pnl_diversity_data)} generations")
    print()

# Step 5: Display sample results
print("5. Sample PnL diversity data:")
print(pnl_diversity_data.head(10))
print()

# Step 6: Display summary statistics
print("6. Summary statistics:")
print(f"   Valid individuals:")
print(f"      Range: {pnl_diversity_data['valid_individuals'].min():.0f} - {pnl_diversity_data['valid_individuals'].max():.0f}")
print(f"      Mean:  {pnl_diversity_data['valid_individuals'].mean():.1f}")
print()
print(f"   Mean correlation:")
print(f"      Initial (gen 0): {pnl_diversity_data['pnl_corr_mean'].iloc[0]:.4f}")
print(f"      Final (gen 50):  {pnl_diversity_data['pnl_corr_mean'].iloc[-1]:.4f}")
print(f"      Overall mean:    {pnl_diversity_data['pnl_corr_mean'].mean():.4f}")
print(f"      Range:           [{pnl_diversity_data['pnl_corr_mean'].min():.4f}, {pnl_diversity_data['pnl_corr_mean'].max():.4f}]")
print()
print(f"   Correlation std dev:")
print(f"      Initial (gen 0): {pnl_diversity_data['pnl_corr_std'].iloc[0]:.4f}")
print(f"      Final (gen 50):  {pnl_diversity_data['pnl_corr_std'].iloc[-1]:.4f}")
print(f"      Overall mean:    {pnl_diversity_data['pnl_corr_std'].mean():.4f}")
print()

# Step 7: Save results
print("7. Saving results...")
pnl_diversity_data.to_csv("pnl_diversity_test.csv", index=False)
print("   ✓ Data saved to: pnl_diversity_test.csv")
print()

# Step 8: Generate visualization
print("8. Generating visualization...")
DiversityVisualizer.plot_pnl_diversity(
    pnl_diversity_data,
    save_path="pnl_diversity_test.png",
    show=False
)
print("   ✓ Plot saved to: pnl_diversity_test.png")
print()

print("="*80)
print("✅ PnL diversity analysis complete!")
print("="*80)
print()
print("Interpretation:")
print("- Mean correlation close to 1.0 → Individuals have similar trading behavior")
print("- Mean correlation close to 0.0 → Individuals have diverse trading behavior")
print("- High std dev → Mix of similar and diverse individuals in population")
print("- Low std dev → Consistent correlation across all pairs")
